### ISSUE TITLE
Each time "ms_kosmos2" is used, an internet connection is required, which results in the inability to utilize this feature offline.

### ISSUE THREAD

**Issue by roobt233** [Hangover3832/ComfyUI-Hangover-Nodes#15]
Thank you for your selfless dedication; I hope we can resolve this issue.

**Comment by Hangover3832** [comment]
I just unplugged the network cable from my computer, having no issues starting ComfyUI and using kosmos2 offline. Note that the model is stored in some cache folder (user\.cache\huggingface\hub\ on Windows 10). May it be that this resource becomes unavailable if you are offline? Please provide more information, os, error message etc.

**Comment by roobt233** [comment]
I retested it once and it works offline, I did it by mistake, thank you for your kind answer, the node is great and works well!
