### ISSUE TITLE
'MsKosmos2' object has no attribute 'model'

### ISSUE THREAD

**Issue by fdtory** [Hangover3832/ComfyUI-Hangover-Nodes#18]
I really wanted to try this out, but I couldn't get it running. I'm missing the model, and it's not downloading automatically. If I downloaded itmanually, where should I put it?

Error occurred when executing MS kosmos-2 Interrogator:

'MsKosmos2' object has no attribute 'model'

File "***ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "***ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "***ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "***ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hangover-Nodes\ms_kosmos2.py", line 49, in interrogate
if (self.model == None) or (self.processor == None) or (self.modelname != huggingface_model) or (device != self.device):
^^^^^^^^^^

**Comment by Hangover3832** [comment]
By default, the models are stored in "<userhome>\.cache\huggingface\hub" (Windows).
Can you please try to switch to the "alt_model_location" branch to see if that will solve your issue? This will change the location of the model to the "ComfyUI/models" folder.
Alternatively, you can change to following lines in ms_kosmos2.py:
```
56:              self.model = AutoModelForVision2Seq.from_pretrained(huggingface_model, cache_dir="ComfyUI/models").to(dev)
57:`             self.processor = AutoProcessor.from_pretrained(huggingface_model, cache_dir="ComfyUI/models")

```

**Comment by Hangover3832** [comment]
There was a similar issue here #12 by za-wa-n-go that seems to be resolved uncommented. Perhaps this user knows more about this?

**Comment by Hangover3832** [comment]
Probably a problem with transformers, must be >=4.35.0.
