### ISSUE TITLE
Kosmos 2.5 model appears to have been released - Possible to incorporate it?

### ISSUE THREAD

**Issue by CCpt5** [Hangover3832/ComfyUI-Hangover-Nodes#23]
Hello,

Thanks for your time and effort on this node!

I noticed that Microsoft quietly dropped the model for Kosmos 2.5 yesterday here: https://github.com/microsoft/unilm/tree/master/kosmos-2.5 
https://huggingface.co/microsoft/kosmos-2.5

The paper was published last September: https://arxiv.org/abs/2309.11419

Curious if you have plans to make it usable with this node or for ComfyUI in any fashion?

Thanks for any info!!

(Edit: Looks like you may be able to just swap in the new model)

**Comment by Hangover3832** [comment]
Thank you for pointing this out, but I will not implement this right now, since it uses Flash Attention 2 which limits the usage quite a lot.
